### ISSUE TITLE
Interface the Temperature Sensor

### ISSUE THREAD

**Issue by mikeshams** [sadgunakarri/capstone-project#4]

**Comment by mikeshams** [comment]
**You need to demonstrate it asap**

**Comment by mikeshams** [comment]
1. What issues did you or others might face with connection of the temperature sensor to the BBB in terms of Hardware and Software?

**Comment by sadgunakarri** [comment]
> 1. What issues did you or others might face with the connection of the temperature sensor to the BBB in terms of Hardware and Software?

Hardware problems
 1. Pinouts were not mentioned on PCB so we needed to take care of them by checking Datasheet.
 2. As there's no power indicator, we always needed to recheck whether all connections are correct or not.

Software problems
1. No proper library is available for C Programming Language.
2. No Proper support by the manufacturer for the Beaglebone platform.
3. I2C protocol use repeated start condition which we were unable to figure out how to do with Beaglebone and C programming and also no support was available for that.

**Comment by mikeshams** [comment]
not very satisfied after two weeks delay
