### ISSUE TITLE
Interfacing speaker to Beaglebone

### ISSUE THREAD

**Issue by mikeshams** [sadgunakarri/capstone-project#5]

**Comment by supbhatoa07** [comment]
1.To connect the buzzer with BBB we first need to initiate the gpio pins. We can do this using iolib libraries. In software we have to define the output pins in c code, where we have connected buzzer. I faced some issue to enable the pins but i did research on iolib libraries and was able to use  required function for this interface.

2. the beep of buzzer is depends upon how long the pin is high for buzzer. In other words i can say by changing the delay in between the pin i can change the frequency of beep.
