### ISSUE TITLE
Interface Camera to Beaglebone

### ISSUE THREAD

**Issue by mikeshams** [sadgunakarri/capstone-project#7]

**Comment by mikeshams** [comment]
What issues did you or others might face when connecting the BBB to the Camera in terms of hardware and software?
How did you resolve them?

**Comment by sadgunakarri** [comment]
> What issues did you or others might face when connecting the BBB to the Camera in terms of hardware and software?
> How did you resolve them?

Hardware issue

Sometimes if the camera doesn't start external power source might be required.

Software

Installing OpenCV libraries are little difficult, better internet connection to BBB is required.
Minimal C resources are available for the camera.
C++ or python may have to be used to use the camera.
